### ISSUE TITLE
Incompatible integer to pointer conversion sending 'bool' to parameter of type 'NSString *' in iOS

### ISSUE THREAD

**Issue by etiks3** [vuk/cordova-plugin-notch#1]
Cordova: 8.1
Node:6
Hybrid project.

Hi there,
Thanks for proposing this plugin. It will avoid a lot of extra code. Unfortunately, on testing with a real device: iPhoneX, XCode report this exception:
"Incompatible integer to pointer conversion sending 'bool' to parameter of type 'NSString *'"
![Screen Shot 2019-04-12 at 14 11 00](https://user-images.githubusercontent.com/22254037/56036423-1fcdc000-5d2d-11e9-97c4-84c5bce4a1a7.png)
I've used it in the 'deviceready' function as:
if(cordova.plugin.Notch.has(){
    // myFunction...
})
Could you please help me on that? 

Thanks.

Sylvain

**Comment by vuk** [comment]
When I get some time, I'll continue testing this. I'll keep this issue opened until I do. Thanks

**Comment by vuk** [comment]
This is now fixed. Plugin name is changed, so you may have to update it
